### PR TITLE
fix to display images in questions

### PR DESCRIPTION
**Pull request by semteacher**
I have investigated an issue (https://github.com/middlebury/moodle-mod_adaptivequiz/issues/42) that @Andmat7 found. As I understand he is right - there is no correct coursemodule instance info there. As I compared to conventional quiz - they get $cm only from attempt.
However - there is no such method in this module.
So, I decide to retrieve all necessary fields directly using existing info. And got some success. Images now have been loaded for me... Notice: was lack of testing - I have had not enough ADPQ quizzes instances (Actually, I do this job "just for fun" - I am no longer involved in project were ADPQ module was used).

### CODE REVIEW

**Comment by semteacher** [comment]
Due to lack of testing - I have just comment original code (with errors) and add my solution

**Comment by euneuber** [comment]
I can confirm your fix works for me! Thank you very much!

**Comment by guptsachin** [comment]
I tried this solution and I encountered two issues. One is the existing one and another is permission issue while trying to open an image in the new tab with student role. 

I did some investigation and found that course id is still incorrect and when I'm hardcoding course id then I can see image but second issue still there. Any guess what is causing this issue.

**Comment by Khalidkabchi** [comment]
Hello everyone,
I hope you are all doing well!
Let me first introduce myself: my name is Khalid KABCHI, Moroccan and I am preparing a thesis about adaptive testing (specifically in physics).
I plan to create an adaptive test but I find huge difficulties in this sense.
For that can you help me to create my own adaptive test? 
khalid.kabchi@gmail.com

**Comment by adamfranco** [comment]
Thank you for submitting this PR. This repository is now archived: The sponsor of this plugin, Middlebury College, is no longer using Moodle. Development is continuing on other forks of the project. See https://moodle.org/plugins/mod_adaptivequiz for more information and latest releases.

**Pull request closed without merging**
